import * as stylex from '@stylexjs/stylex'
import { colors, fonts, motion, radius, shadows, sizing, spacing } from './tokens.stylex'

export const globalStyles = stylex.create({
  appShell: {
    minHeight: '100vh',
    backgroundColor: colors.background,
    color: colors.text,
    fontFamily: fonts.sans,
    backgroundImage: 'radial-gradient(circle at top, rgba(126, 224, 195, 0.16), transparent 26%), linear-gradient(180deg, #081118 0%, #071118 45%, #0a1720 100%)',
  },
  page: {
    minHeight: '100vh',
  },
  pageStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xxxl,
    paddingBottom: spacing.xxxl,
  },
  container: {
    width: '100%',
    maxWidth: sizing.container,
    marginInline: 'auto',
    paddingInline: spacing.lg,
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xl,
  },
  heroSection: {
    paddingTop: '8rem',
  },
  gridTwo: {
    display: 'grid',
    gap: spacing.xl,
    gridTemplateColumns: 'repeat(auto-fit, minmax(18rem, 1fr))',
    alignItems: 'start',
  },
  gridThree: {
    display: 'grid',
    gap: spacing.lg,
    gridTemplateColumns: 'repeat(auto-fit, minmax(16rem, 1fr))',
  },
  gridCards: {
    display: 'grid',
    gap: spacing.lg,
    gridTemplateColumns: 'repeat(auto-fit, minmax(16rem, 1fr))',
  },
  panel: {
    backgroundColor: colors.surfaceSoft,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.line,
    borderRadius: radius.lg,
    boxShadow: shadows.card,
    backdropFilter: 'blur(14px)',
  },
  panelStrong: {
    backgroundColor: colors.surface,
    borderColor: colors.lineStrong,
  },
  panelInset: {
    backgroundColor: colors.backgroundAlt,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.line,
    borderRadius: radius.md,
  },
  sectionSurface: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.md,
  },
  eyebrow: {
    fontSize: '0.75rem',
    textTransform: 'uppercase',
    letterSpacing: '0.22em',
    color: colors.accent,
  },
  title: {
    fontFamily: fonts.display,
    fontSize: 'clamp(2.5rem, 6vw, 4.5rem)',
    lineHeight: 1,
    letterSpacing: '-0.04em',
    margin: 0,
  },
  sectionTitle: {
    fontFamily: fonts.display,
    fontSize: 'clamp(1.9rem, 4vw, 3rem)',
    lineHeight: 1.05,
    letterSpacing: '-0.03em',
    margin: 0,
  },
  body: {
    color: colors.textMuted,
    fontSize: '1rem',
    lineHeight: 1.7,
    margin: 0,
  },
  meta: {
    color: colors.textSoft,
    fontSize: '0.78rem',
    textTransform: 'uppercase',
    letterSpacing: '0.18em',
  },
  buttonRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  buttonBase: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    borderRadius: radius.pill,
    paddingInline: spacing.lg,
    paddingBlock: spacing.sm,
    fontSize: '0.78rem',
    lineHeight: 1.2,
    letterSpacing: '0.2em',
    textTransform: 'uppercase',
    textDecoration: 'none',
    transitionProperty: 'transform, background-color, border-color, color, opacity',
    transitionDuration: motion.base,
    transitionTimingFunction: motion.ease,
    borderWidth: '1px',
    borderStyle: 'solid',
    cursor: 'pointer',
  },
  buttonPrimary: {
    color: colors.background,
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  buttonSecondary: {
    color: colors.text,
    backgroundColor: 'transparent',
    borderColor: colors.lineStrong,
  },
  field: {
    width: '100%',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.line,
    borderRadius: radius.md,
    backgroundColor: colors.backgroundAlt,
    color: colors.text,
    paddingInline: spacing.md,
    paddingBlock: spacing.md,
    fontFamily: fonts.sans,
    fontSize: '1rem',
    lineHeight: 1.5,
    '::placeholder': {
      color: colors.textSoft,
    },
  },
  cardTitle: {
    fontFamily: fonts.display,
    fontSize: '1.35rem',
    lineHeight: 1.15,
    letterSpacing: '-0.02em',
    margin: 0,
  },
  prose: {
    maxWidth: sizing.prose,
    color: colors.textMuted,
    fontSize: '1rem',
    lineHeight: 1.8,
  },
  list: {
    display: 'grid',
    gap: spacing.md,
    paddingLeft: spacing.lg,
    margin: 0,
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    borderRadius: radius.pill,
    backgroundColor: colors.accentWash,
    color: colors.accent,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.lineStrong,
    paddingInline: spacing.sm,
    paddingBlock: spacing.xs,
    fontSize: '0.72rem',
    textTransform: 'uppercase',
    letterSpacing: '0.18em',
  },
  surfaceRow: {
    display: 'grid',
    gap: spacing.md,
  },
  anchorReset: {
    color: 'inherit',
    textDecoration: 'none',
  },
  separatorLine: {
    height: '1px',
    width: '100%',
    backgroundColor: colors.line,
  },
  siteHeader: {
    position: 'sticky',
    top: 0,
    zIndex: 30,
    backdropFilter: 'blur(18px)',
    backgroundColor: 'rgba(7, 17, 24, 0.74)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: colors.line,
  },
  siteFooter: {
    marginTop: spacing.xxxl,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.line,
    backgroundColor: 'rgba(7, 17, 24, 0.6)',
  },
})
